### ISSUE TITLE
Refactor the airflow pipeline endpoints into a blueprint

### ISSUE THREAD

**Issue by SamSedivy** [x-atlas-consortia/ubkg-api#11]
The entity_CRUD blueprint is getting big and we can move the airflow pipeline endpoints into their own blueprint to keep it organized

**Comment by AlanSimmons** [comment]
@SamSedivy Is ubkg-api the correct repo for this issue?

**Comment by SamSedivy** [comment]
> The entity_CRUD blueprint is getting big and we can move the airflow pipeline endpoints into their own blueprint to keep it organized

No it was a mistake. It should be in ingest-api. I moved it there.
