### ISSUE TITLE
Modify SenNet Breast organ

### ISSUE THREAD

**Issue by maxsibilla** [x-atlas-consortia/ubkg-api#113]
Currently we have the following entry in organs for "Breast" from the UBKG:
```
    {
        "code": "C030027",
        "organ_cui": "C0006141",
        "organ_uberon": "UBERON:0000310",
        "rui_code": "BS",
        "sab": "SENNET",
        "term": "Breast"
    }
```

After discussing with the team from Indiana we learned that the RUI tool supports  “Mammary Gland (Left)” and “Mammary Gland (Right)“.

Is it possible to modify this existing entry into a left and right breast? Are there UBERON and CUI codes to support that? Would it be better to change this to be "Mammary Gland" instead of "Breast"?

@bhonick @AlanSimmons @shirey

**Comment by maxsibilla** [comment]
Notes regarding the RUI tool

- The 2 digit code is not required, it is used on the HuBMAP side as a quick lookup for the UBERON or FMA term (https://github.com/hubmapconsortium/ingest-ui/blob/5bce9fba3162a64faf0433a541fd8a465a883f87/src/src/constants.jsx#L139)
- The UBERON code for "Mammary Gland" is http://purl.obolibrary.org/obo/UBERON_0001911
  - An FMA code is required to specify left or right and would need to be stored instead
  - Mammary Gland L -http://purl.org/sig/ont/fma/fma57991
  - Mammary Gland R - http://purl.org/sig/ont/fma/fma57987

**Comment by maxsibilla** [comment]
After discussing with the Indiana team I have applied a band-aid fix to allow for RUI registration of Breast `Blocks`. I have added a check for this organ and set the RUI organ to be "Mammary Gland, L"

**Comment by AlanSimmons** [comment]
So, do we add codes for left and right mammary glands and delete the code for breast in SenNet?

**Comment by maxsibilla** [comment]
@AlanSimmons I added this as an agenda item for the CODCC meeting tomorrow

**Comment by AlanSimmons** [comment]
# In source

SENNET:C030082 - Mammary gland (left) - cross-referenced to FMA:57991
SENNET:C030083 - Mammary gland (right) - cross-referenced to FMA:57987

These will be available in the next release of the HuBMAP/SenNet UBKG.
