### ISSUE TITLE
Compile new ubkg-api PyPI package

### ISSUE THREAD

**Issue by AlanSimmons** [x-atlas-consortia/ubkg-api#140]
Related to PR [139](https://github.com/x-atlas-consortia/ubkg-api/pull/139).

Recompile the ubkg-api PyPI package for both the HuBMAP and Data Distillery instances.

**Comment by yuanzhou** [comment]
FYI, the PR #139 changes will be wrapped into the same v2.1.5 release that was drafted earlier. 
<img width="1039" alt="Screenshot 2024-07-19 at 10 49 56 AM" src="https://github.com/user-attachments/assets/866aaaec-35d4-41da-b589-2a62dc40516e">
