### ISSUE TITLE
Add secondary assay types for SenNet

### ISSUE THREAD

**Issue by maxsibilla** [x-atlas-consortia/ubkg-api#26]
Currently in SenNet we only support primary data types but we need to add additional secondary data types that are supported by the dataset pipeline processing. Some of these secondary data types include "snRNAseq-10xGenomics-v3" and salmon_sn_rnaseq_10x".

My proposal is to support all data types supported by HuBMAP where `primary` is false but need further confirmation on this.

**Comment by AlanSimmons** [comment]
@maxsibilla @shirey 

A number of the HuBMAP secondary assay types in the assay_types.yaml file are artifacts that have been deprecated (if, by deprecated, I mean "no longer present when you search the provenance database").  

I recommend confirming the pipelines from HuBMAP that SenNet has stated explicitly that it will support and add data on these assays to the SenNet ontology. Otherwise, we may just be copying over what may be old HuBMAP cruft.

**Comment by maxsibilla** [comment]
@AlanSimmons thank you for pointing that out, yes we should definitely then get a more fine-grained list

**Comment by AlanSimmons** [comment]
I asked Brendan to identify the set of pipelines that are common to HuBMAP and SenNet.

**Comment by AlanSimmons** [comment]
After the April 26 CODCC meeting, we agreed to add all current pipelines information from the HuBMAP application ontology to the SenNet application ontology.

**Comment by AlanSimmons** [comment]
I added to the SENNET ontology information on all datasets (assay types), both primary and derived, from HuBMAP.

**Comment by maxsibilla** [comment]
> I added to the SENNET ontology information on all datasets (assay types), both primary and derived, from HuBMAP.

@AlanSimmons I don't think all primary assay types should be added from HuBMAP since we have already gone through the process of curating which ones SenNet will support. The current ~17 primary assay types are all we need. Adding additional ones will modify the UI in the portal.

**Comment by AlanSimmons** [comment]
I'm not sure what you want here. You asked for the secondary assay types. Many of the secondary assay types derive from primary assay types, including primary assay types from HuBMAP. I asked for a curated list of secondary assay types from SenNet. I was instructed during the last CODCC meeting to add everything from HuBMAP to SenNet. I did this.

If you want a specific set of secondary assays from HuBMAP to go into SenNet, then please provide an explicit list of these assays in this card.

**Comment by AlanSimmons** [comment]
@maxsibilla 
I removed from the SenNet ontology all primary and derived assay types except for the following:


Primary | Secondary
-- | --
Bulk RNA-seq | salmon_rnaseq_bulk
CITE-seq |  
CODEX | codex_cytokit
CODEX | codex_cytokit_v1
CosMX (RNA) |  
DBiT-seq |  
FACS - Fluorescence-activated Cell Sorting |  
LC-MS |  
Lightsheet |  
Mint-ChIP |  
SASP |  
Stained Slides |  
Visium |  
bulk-RNA | salmon_rnaseq_bulk
scRNA-seq | salmon_rnaseq_10x
snATAC-seq | sn_atac_seq
snRNA-seq |

**Comment by bhonick** [comment]
Primary: snATACseq -> Secondary: snATAC-seq [SnapATAC]  -- snapatac_atacseq_snare?
Primary: snRNAseq -> snRNAseq [Salmon] -- salmon_rnaseq_snare?

**Comment by maxsibilla** [comment]
@AlanSimmons did `salmon_rnaseq_10x` make it into the update CSVs?

**Comment by AlanSimmons** [comment]
@SamSedivy FYI

**Comment by AlanSimmons** [comment]
For now, the `salmon_rnaseq_10x` derived dataset type will be associated with the `scRNA-Seq` primary dataset type.
