### ISSUE TITLE
Endpoint for Organ data

### ISSUE THREAD

**Issue by AlanSimmons** [x-atlas-consortia/ubkg-api#3]
Requested response in the form of:
```
{
	"code": "C030026",
	"sab": "SENNET",
	"term": "Brain",
	"rui_code": "BR"
}
```

**Note**: The property `rui_code` can be named anything

**Comment by bherr2** [comment]
Not 100% sure what rui_code is, but you should use the uberon terms associated with the rui supported reference organs identified here: <https://github.com/hubmapconsortium/portal-ui/tree/main/context/app/organ>

**Comment by bherr2** [comment]
There's also this: <https://github.com/hubmapconsortium/ingest-ui/blob/main/src/src/constants.jsx#L166-L201> but the other link may work better.

**Comment by maxsibilla** [comment]
@shirey Should we drop support of the two digit organ codes and use uberon instead for SenNet?

**Comment by AlanSimmons** [comment]
So many different sources of truth!

I'll need to make sure that the application ontology lines everything up.

**Comment by AlanSimmons** [comment]
The nice thing about the references in portal-ui is that they list both the UBERON and ASCTB codes.

**Comment by AlanSimmons** [comment]
Some issues:
1. The RUI [references](https://github.com/hubmapconsortium/portal-ui/tree/main/context/app/organ) are to HuBMAP. Will SenNet have its own set of references?
2. The SenNet [organ_types.yaml](https://github.com/sennetconsortium/search-api/blob/main/src/search-schema/data/definitions/enums/organ_types.yaml) file a number of organs that are either not in the HuBMAP reference or are at a higher level of resolution (usually with respect to laterality)


organ | closest equivalent in HuBMAP RUI reference |UBERON in RUI reference|possible UBERON
-- | --| --|--
Adipose Tissue | none|| UBERON:0001013
Kidney (Left) | Kidney| UBERON:0002113|UBERON:0004538
Kidney (Right)|Kidney|UBERON:0002113|UBERON:0004539
Lung (Left)|Liver| UBERON:0002048 |UBERON:0002168
Lung (Right)|Liver| UBERON:0002048|UBERON:0002167
Ovary (Left)|Ovary|UBERON:0000992|UBERON:0002119
Ovary (Right)|Ovary|UBERON:0000992|UBERON:0002119
Other|none||?

I think that Other might be a problem.

**Comment by maxsibilla** [comment]
Currently we pass the 2-digit organ code to the CCF-RUI tool and the organs that are supported in SenNet are largely supported by HuBMAP. To my knowledge the only organs not supported by the CCF-RUI tool in SenNet are:
Adipose, Blood, Breast, Lymph Node, Muscle, and Other

**Comment by maxsibilla** [comment]
@AlanSimmons Is the action item for this card to create a new endpoint for Organ Types? I just want to make sure I am following along with #8

**Comment by AlanSimmons** [comment]
@maxsibilla @shirey @SamSedivy @ChuckKollar 
I think that the workflow would be:
1. Refactor the ubkg-api
2. Add a new endpoint for the ubkg-api for organ type (this card)
3. Convert the current call for organ type in ingest api to call the endpoint in ubkg-api

In other words, I think that new endpoints are to be added to the refactored API. However, if we need these immediately, then we could do numbers and 3 in the existing ubkg-api and then refactor. That seems like double work, though.

**Comment by AlanSimmons** [comment]
The Cypher query is attached:
[organ info cypher.txt](https://github.com/x-atlas-consortia/ubkg-api/files/11092882/organ.info.cypher.txt)

Results for SENNET attached:
[SENNET organ info.csv](https://github.com/x-atlas-consortia/ubkg-api/files/11092890/SENNET.organ.info.csv)


The endpoint will need to be parameterized for application context--i.e., SENNET or HUBMAP. Both application ontologies use the same code for the organ parent--i.e., C000008.

**Comment by AlanSimmons** [comment]
@libpitt identified a duplication issue: multiple array elements for Muscle. This is similar to an issue that I resolved a couple of weeks ago. It will require an update to the cypher query, which I attach.

# Explanation of problem
SENNET C030036 (Muscle) has a cross-reference to UBERON 0005090, which is itself cross-referenced to UMLS C4083049. UMLS C4083049 is also the cross-reference for two other UBERON codes. Because the Cypher query works with concept CUIs, looking for "the UBERON code associated with the concept" returns all 3 codes.

![image](https://user-images.githubusercontent.com/10928372/231827640-1fc7bb0c-e45f-4dc5-a227-7b57c3772d6a.png)


# Solution
Update the Cypher query with the contents of the attached file. The query has to handle as special cases SENNET codes that map to UBERON codes that map to UMLS CUIs that map to multiple UBERON codes.


## Validation
This is an export of the results of the query against my dev neo4j instance.
[export.csv](https://github.com/x-atlas-consortia/ubkg-api/files/11224369/export.csv)
