### ISSUE TITLE
Organ endpoint response should include the UBERON code

### ISSUE THREAD

**Issue by AlanSimmons** [x-atlas-consortia/ubkg-api#33]
FYI @ icaoberg

Related to this [PR] (https://github.com/hubmapconsortium/search-api/pull/521)

# Statement of Problem
The [organ](https://ontology.api.hubmapconsortium.org/organs?application_context=HUBMAP) endpoint of the UBKG API is intended to replace [organ_types.yaml ](https://github.com/hubmapconsortium/search-api/blob/main/src/search-schema/data/definitions/enums/organ_types.yaml) as the source of truth on organ data. To support CFDE reporting, the endpoint should include the UBERON code for organs.

# Solution
This will require a straightforward update to the organ endpoint code in the API manager.

The organ UBERON code is part of the application ontology. The Cypher query behind the organ endpoint already returns the UBERON code (see the **get_organ_types** function [here](https://github.com/x-atlas-consortia/ubkg-api/blob/main/src/neo4j_manager.py)). The endpoint code merely needs to include the UBERON code in the response.

**Comment by shirey** [comment]
This appears to have been completed by PR https://github.com/x-atlas-consortia/ubkg-api/pull/52.  Please review the endpoint on the PROD HuBMAP/SenNet ontology API instance to ensure that this has made its way to production.

**Comment by AlanSimmons** [comment]
It did. From the API endpoint in production.

![image](https://github.com/x-atlas-consortia/ubkg-api/assets/10928372/7087ff1d-d345-448b-8fd3-3b7589a6514a)
