### ISSUE TITLE
New endpoint: resolve HGNC aliases and previous IDs

### ISSUE THREAD

**Issue by AlanSimmons** [x-atlas-consortia/ubkg-api#45]
# Statement of problem

Genes in HGNC can be identified by:

- current HGNC ID
- symbol
- alias
- prior symbols

Provide alias and prior IDs based on the current HGNC ID.

# Solution

It appears that information on previous symbols and aliases for HGNC genes is available in UBKG as terms of differing semantic types. For example, the previous symbol corresponds to the name of a term node with relationship type NS.

The UBKG API will need a new endpoint that organizes HGNC information by type.

![image](https://github.com/x-atlas-consortia/ubkg-api/assets/10928372/beaade2b-60c1-4ba7-b310-0690bc42d8c1)
<img width="421" alt="image" src="https://github.com/x-atlas-consortia/ubkg-api/assets/10928372/6aba31d4-cf94-4e83-97c9-92f751010bd1">

**Comment by AlanSimmons** [comment]
Sample Cypher query for HGNC HGNC:7178:

```
match(t:Term)<-[r]-(c:Code) where type(r) in ['PT','ACR','SYN','NS'] AND c.CodeID='HGNC HGNC:7178' RETURN c.CODE AS Code, CASE type(r) WHEN 'PT' THEN 'name' WHEN 'ACR' THEN 'symbol' WHEN 'NS' THEN 'previous' WHEN 'SYN' THEN 'alias' ELSE type(r) END AS type, t.name AS value ORDER BY type(r)
```

result:
```
[
  {
    "Code": "HGNC:7178",
    "type": "symbol",
    "value": "MMRN1"
  },
  {
    "Code": "HGNC:7178",
    "type": "previous",
    "value": "MMRN"
  },
  {
    "Code": "HGNC:7178",
    "type": "name",
    "value": "multimerin 1"
  },
  {
    "Code": "HGNC:7178",
    "type": "alias",
    "value": "EMILIN4"
  },
  {
    "Code": "HGNC:7178",
    "type": "alias",
    "value": "GPIa*"
  },
  {
    "Code": "HGNC:7178",
    "type": "alias",
    "value": "ECM"
  }
]
```

**Comment by ChuckKollar** [comment]
https://github.com/x-atlas-consortia/ubkg-api/issues/45
