### ISSUE TITLE
Re-add MIBI to SenNet ontology

### ISSUE THREAD

**Issue by maxsibilla** [x-atlas-consortia/ubkg-api#48]
I believe during the most recent updating of the data types in SenNet MIBI (Multiplex Ion Beam Imaging) was removed and missed during our validation.

**Comment by AlanSimmons** [comment]
Fortunately, I made a backup.

Should I also add back the MIBI [DeepCell + SPRM] derived dataset?

**Comment by maxsibilla** [comment]
I would say yes, thank you
