### ISSUE TITLE
Add salmon_sn_rnaseq_10x to SenNet data types

### ISSUE THREAD

**Issue by maxsibilla** [x-atlas-consortia/ubkg-api#50]
We currently have the assay type `salmon_rnaseq_10x` but we need to add `salmon_sn_rnaseq_10x`:
```
{
	"alt-names": ["salmon_rnaseq_10x_sn"],
	"contains-pii": false,
	"data_type": "salmon_sn_rnaseq_10x",
	"dataset_provider": "SenNet IEC",
	"description": "snRNA-seq [Salmon]",
	"primary": false,
	"vis-only": false,
	"vitessce-hints": ["rna", "is_sc"]
}
```

**Comment by AlanSimmons** [comment]
Added back to source:

- salmon_sn_rnaseq_10x: derived dataset
- snRNAseq-10xGenomics-v3: associated primary dataset

**Comment by AlanSimmons** [comment]
In latest CSVs here: https://g-24f5cc.09193a.5898.dn.glob.us/projects/data-distillery/Validated/CSV/HuBMAP-SenNet/HMSN%2008Jun2023.zip
