### ISSUE TITLE
Add 'Upload' as an Entity Type for SenNet

### ISSUE THREAD

**Issue by maxsibilla** [x-atlas-consortia/ubkg-api#77]
This additional entity type should be returned by this endpoint: https://ontology-api.dev.hubmapconsortium.org/valueset?parent_sab=SENNET&parent_code=C000012&child_sabs=SENNET

**Comment by AlanSimmons** [comment]
Blocked until these cards are completed:
- [This one](https://github.com/x-atlas-consortia/hs-ontology-api/issues/14)
- [This one](https://github.com/x-atlas-consortia/hs-ontology-api/issues/21)

**Comment by AlanSimmons** [comment]
Added to source spreadsheet.

**Comment by AlanSimmons** [comment]
SENNET:C050022
