### ISSUE TITLE
Add 10x Multiome as Assay Type for SenNet

### ISSUE THREAD

**Issue by maxsibilla** [x-atlas-consortia/ubkg-api#81]
In order to facilitate basic ingestion of multiome data we would like to add 10x Multiome as a primary assay type to the `/datasets` endpoint. At this moment we do not need secondary/derived assay types related to this. We just want this to allow users to select it from the drop down menu in the Data Sharing Portal.

**Comment by AlanSimmons** [comment]
Duplicate of [this card](https://github.com/x-atlas-consortia/ubkg-neo4j/issues/28), which was on hold until 21 September.

Closing this issue.
