### ISSUE TITLE
Update UBKG API to work against a Neo4j 5.x database

### ISSUE THREAD

**Issue by shirey** [x-atlas-consortia/ubkg-api#87]
Create a new version of the UBKG API that will work against Neo4j 5.x.  For now create a "neo4jv5" branch for this work and don't merge into `main` or `dev` yet.  This branch can be released on the new Data Distillery setup created by [DevOps #115](https://github.com/hubmapconsortium/devops/issues/115).  To do this:

  - Update the Neo python library/driver to the matching 5.x version
  - Test all endpoints/neo4j queries to make sure they still work in Neo4j 5

**Comment by ChuckKollar** [comment]
OpenJDK 64-Bit Server VM warning: Option UseBiasedLocking was deprecated in version 15.0 and will likely be removed in a future release.

**Comment by ChuckKollar** [comment]
Issue: Aggregation column contains implicit grouping expressions

This occurs in a Cyber query here:
https://github.com/x-atlas-consortia/ubkg-api/blob/1f841501af8050c50377ca439f491ea0df421414/src/ubkg_api/common_routes/common_neo4j_logic.py#L437

**Comment by ChuckKollar** [comment]
Updated to use neo4j 5.15.0. Tests run. and documented gross failures noted.

IMPORTANT: We should have more complete tests. Probably Alan can specify what he thinks is important and I can make some code for them.
