### ISSUE TITLE
Dockerized version of UBKG service

### ISSUE THREAD

**Issue by shirey** [x-atlas-consortia/ubkg-api#89]
Create a Docker image of this UBKG service to run as we run other RESTful services.

Install the service on the new VM created by [x-atlas-consortia/devops #26](https://github.com/sennetconsortium/devops/issues/26) accessible via the Gateway service set up by [x-atlas-consortia/ubkg-api #90](https://github.com/x-atlas-consortia/ubkg-api/issues/90)

**Comment by yuanzhou** [comment]
https://github.com/x-atlas-consortia/ubkg-api/pull/96
