### ISSUE TITLE
Add `/status` endpoint

### ISSUE THREAD

**Issue by yuanzhou** [x-atlas-consortia/ubkg-api#94]
With the ubkg-api itself deployed as an API for Data Distillery, we need to add this `/status` endpoint similar to other APIs to show the BUILD, VERSION, and Neo4j connection connection status. 

Similar to https://ontology.api.hubmapconsortium.org/status
```
{"build":"main:4622be8","neo4j_connection":true,"version":"1.4.10"}
```

https://github.com/x-atlas-consortia/hs-ontology-api/blob/4622be8a94a1e679765dad8a6e82491dd6cf16a0/src/main.py#L71-L85

**Comment by yuanzhou** [comment]
Branch off https://github.com/x-atlas-consortia/ubkg-api/tree/neo4jv5. This `neo4jv5` will be the new main branch once all is ready. Currently it contains all the Docker work Karl did earlier and lots of API endpoint updates from 
Alan. 

The BUILD number can be generated using the same script: https://github.com/x-atlas-consortia/hs-ontology-api/blob/main/generate-build-version.sh

**Comment by ChuckKollar** [comment]
PR: https://github.com/x-atlas-consortia/ubkg-api/pull/101
